-- What is the total revenue generated by male customers compared to female customers?
SELECT gender, SUM(purchase_amount) as purchase_sum
FROM customer
GROUP BY gender
ORDER BY purchase_sum DESC;

-- Which customers received a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- What are the 5 products with the highest average rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as review_mean
FROM customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Comparing average purchase values ​​between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) as purchase_mean
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY purchase_mean DESC;

-- Did subscribers spend more? Comparing average spending and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
	   COUNT(customer_id) AS customer_total,
	   ROUND(AVG(purchase_amount), 2) as purchase_mean, 
       ROUND(SUM(purchase_amount), 2) as purchase_total
FROM customer
GROUP BY subscription_status
ORDER BY purchase_total DESC, purchase_mean DESC;

-- What are the 5 products with the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	   ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*), 2) AS discount_applied
FROM customer
GROUP BY item_purchased
ORDER BY discount_applied DESC
LIMIT 5;

-- Segmenting customers into New, Returning, and Loyal based on the total number of previous purchases and show the count for each segment.
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END as client_type,
    COUNT(*) as client_count
FROM customer
GROUP BY client_type
ORDER BY client_count DESC;

-- What are the 3 most purchased products in each category?
WITH rank_products as (
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) as purchase_total,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY purchase_total DESC) as ranking
    FROM customer
    GROUP BY category, item_purchased
)
SELECT *
FROM rank_products
WHERE ranking <= 3;

-- Are customers who buy repeatedly (more than 5 previous purchases) also more likely to repeat?
SELECT COUNT(customer_id) as customers, subscription_status
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY customers DESC;

-- What is the contribution of each age group to revenue?
SELECT age_group, SUM(purchase_amount) as purchase_amount
FROM customer 
GROUP BY age_group
ORDER BY purchase_amount DESC;
